title: Binsa Bhandari # your name (or website title) here
logo: "/images/NewPic.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Orginally fron Jhapa, Nepal, I am a fourth-year student at Seattle Pacific University majoring in Computer Science and minoring in 
  Business Adminstration with a expected graduation date in June 2022. I am well versed in C++, JavaScript, HTML, 
  and CSS. My primary interest is in Web/Mobile Developement and UI/UX Design.
 
  <br><br>
  <a href="https://www.linkedin.com/in/binsabhandari/">View My LinkedIn Profile</a>
  <br>
  <a href="https://blooming-harbor-92058.herokuapp.com/resume.html">View My Resume</a>
  
theme: jekyll-theme-minimal


