title: Binsa Bhandari # your name (or website title) here
logo: "/images/me.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  I am a fourth-year student at Seattle Pacific University majoring in Computer Science and minoring in Business Adminstration. Through my skills in programming and design, I hope to create intuitive software to improve our way of living.
  I am primarily interested in Web/ Mobile Development and UI/UX Design. 

  <br><br
  I am primarily interested in Web/ Mobile Development and UI/UX Design. 
  
  <br><br>
  <a href="https://www.linkedin.com/in/binsabhandari/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
  


