title: Binsa Bhandari # your name (or website title) here
logo: "/images/me.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Orginally fron Jhapa, Nepal, I am a fourth-year student at Seattle Pacific University majoring in Computer Science and minoring in Business Adminstration with a expected graduation date in June 2022. I hope to create software to improve our daily lives through my skills in programming and design. I am well versed in C++, JavaScript, HTML, and CSS. I have created numerous applications using one or a combination of those languages. 
  I am primarily interested in Web/Mobile Developement and UI/UX Design.
 
  <br><br>
  <a href="https://www.linkedin.com/in/binsabhandari/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal


