title: Binsa Bhandari # your name (or website title) here
logo: "/images/me.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a student at Seattle Pacific University majoring in Computer Science and minoring in Business Adminstration. My passion is with computer software. Through my skills in programming and design, i hope to create intuitive software to improve our way of living.
  I am primarily interested in software design and programming – UX/UI Design.

  <br><br>
  Majoring in Computer Science 
  Minoring in Business Adminstration
  <br><br>
  <a href="https://www.linkedin.com/in/binsabhandari/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
