title: Binsa Bhandari # your name (or website title) here
logo: "/images/me.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a fourth-year student at Seattle Pacific University majoring in Computer Science and minoring in Business Adminstration. Through my skills in programming and design, I hope to create intuitive software to improve our way of living.
  I am primarily interested in Web/ Mobile Development and UI/UX Design. 

 
  <br><br>
  <a href="https://www.linkedin.com/in/binsabhandari/">View My LinkedIn Profile</a> 
  


